### PR TITLE
fix: Add "iw" variant of Hebrew language code

### LINKED ISSUE #1457: No equivalent 3-letter language code
## System info
**Operating System**: Docker image alpine:3.18
**Shaka Packager Version**: v3.3.0

## Issue and steps to reproduce the problem

**Packager Command**:
```
/usr/local/bin/packager in=tmp/35ad6424-23c5-4a00-a2a9-c39c41bb0aa1.mp4,stream=1,segment_template=tmp/audio/iw/$Number$.aac,playlist_name=tmp/audio/iw/audio.m3u8,hls_group_id=audio,hls_name=,language=iw in=tmp/d483d2b0-635c-438e-8b65-2ccb35931585.mp4,stream=video,segment_template=tmp/480p/$Number$.ts,playlist_name=tmp/480p/playlist.m3u8 --segment_duration 4 --default_language iw --hls_master_playlist_output tmp/master.m3u8
```
Extra steps to reproduce the problem?
(1) Download [this](https://www.youtube.com/watch?v=Z57acavJjt4) video from youtube with default audio track
(2) Then try to transcode it with shaka-packager

What is the expected result?
**It is expected to be successfully transcoded**
What happens instead?
**It throws error like below**
```
packager_main.cc:624] Failed to initialize packager: 3 (INVALID_ARGUMENT): Unknown/invalid language specified: iw |  
language_utils.cc:136] No equivalent 3-letter language code for iw
```

I need help, please. Thanks in advance

### PR DESCRIPTION
**Pull request by joeyparrish**
We already mapped Hebrew's "heb" to "he", but not to the alternative 2-letter code "iw".

Closes #1457

### CODE REVIEW

**Comment by avelad** [comment]
@joeyparrish should we add the same in Shaka Player?

**Comment by joeyparrish** [comment]
> @joeyparrish should we add the same in Shaka Player?

Yes, if it's missing.  I think these were in sync at one point.

**Comment by joeyparrish** [comment]
@cosmin, the linter hates the formatting in this file, so I'm going to reformat it, which is going to make the diff a nightmare to read.  Sorry about that.

**Comment by joeyparrish** [comment]
Re: Linux CI failures, see https://github.com/shaka-project/shaka-packager/pull/1459

I'll run this one again after that lands.

**Review by cosmin — APPROVED** [review]

**Pull request merged**
