### PR TITLE
fix: Break header installation for the shared library

### LINKED ISSUE #1406: Macro DISALLOW_COPY_AND_ASSIGN include/file.h
Hi Everyone,

is that normal that include/file.h contains this line: 
```c++
#include <packager/macros/classes.h>
``` 

From the README
These are the public headers for libpackager.  They can only reference other
public headers or standard system headers.  They cannot reference internal
headers (in `packager/...`) or third-party dependency headers (in
`packager/third_party/...`).

Is that a mistake or I am missing something ? 

Regards,

### PR DESCRIPTION
**Pull request by zaki699**
include/file.h is breaking header installation for the shared library build.  macros/classes.h must be included to the public headers.

Closes #1406

### CODE REVIEW

**Comment by joeyparrish** [comment]
I started the tests for this... why did you close it?

**Comment by zaki699** [comment]
Hi Joey,

Sorry I made a wrong manip. I reopened it.

Zaki

On May 30, 2024, at 10:31 PM, Joey Parrish ***@***.***> wrote:



I started the tests for this... why did you close it?

**Comment by joeyparrish** [comment]
I edited your PR and added the necessary line (file.h) to packager.h to make sure the `packager_link_test` target can catch macros/classes.h being missing.

**Comment by zaki699** [comment]
Thx for your help. Very appreciated.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joeyparrish** [comment]
Happy to help.  That check really should have caught this, and I created it, so it was the least I could do.

**Comment by zaki699** [comment]
I think the CLA is not working because my git configuration was not setting up correctly and was using the wrong email and user.

Do you mind telling me what to do to fix this ?




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joeyparrish** [comment]
Sure.  I'm going to [the "Details" link](https://github.com/shaka-project/shaka-packager/pull/1407/checks?check_run_id=25623366053) next to the CLA check at the bottom of the PR.  There, I see a list of the contributors from the git commits:

> The following contributors were found for this pull request:
> 
> ✅ https://github.com/shaka-project/shaka-packager/commit/1ef5981e3bb0b84421ee893dd1878391ec93f0ad PR Opener: @zaki699
> ❌ https://github.com/shaka-project/shaka-packager/commit/6fb1ad653dbd1f822bf63c8e1a5bbbef475d6df3 Author: <o***n​@Zakis-MacBook-Pro.local>
> ✅ https://github.com/shaka-project/shaka-packager/commit/1ef5981e3bb0b84421ee893dd1878391ec93f0ad Author: @joeyparrish <joeyparrish​@users.noreply.github.com>

So it's the commit from `...​@Zakis-MacBook-Pro.local` that doesn't match the CLA.  You just need to run `git config` to set your name and email address, then amend the commit in question and force-push the PR branch.

**Comment by zaki699** [comment]
Ok  Now the CLA is validated. 

Thx

**Comment by zaki699** [comment]
It seems that I have somehow managed to remove your previous commit. Do you mind pushing it again ?

Thanks you

**Comment by joeyparrish** [comment]
Done

**Comment by joeyparrish** [comment]
I will merge this if the tests pass, which I fully expect

**Review by joeyparrish — APPROVED** [review]

**Pull request merged**
