### PR TITLE
build: Fix absl log flags being stripped

### LINKED ISSUE #1325: Logging no longer works?
## System info
**Operating System**: Ubuntu 20.04.6 LTS / Debian GNU/Linux 12 (bookworm)
**Shaka Packager Version**: packager version 3e71302b-debug (current `HEAD`)

## Issue and steps to reproduce the problem

**Packager Command**: `./packager --dump_stream_info input=testing.mp4 --v=9`

I have tried all variations of the `--v` flag, I've also tried `vmodule` (deprecated), I've tried combinations with `--minloglevel` and `--stderrthreshold` which are new flags since the build system change but nothing can convince the tool to print more.

I've tried both a `Release` and a `Debug` build off `HEAD`. I can see that the `Debug` build does all the `DCHECK` stuff because if I use it to encrypt/decrypt something it takes longer than the `Release` build. But none of them print anything remotely verbose let alone the "normal" non-verbose output from the previous log system like `Demuxer::Run()` message as seen below.

When I run `./build/packager/packager_test` however I do get the verbose logging output I'm expecting even if the formatting looks a bit off.

```
Running main() from ../packager/third_party/googletest/source/googletest/src/gtest_main.cc
[==========] Running 13 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 13 tests from PackagerTest
[ RUN      ] PackagerTest.Version
[       OK ] PackagerTest.Version (0 ms)
[ RUN      ] PackagerTest.Success
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1703714503.296654 3166804 status.cc:76] 1 (UNKNOWN): Job uninitialized
I0000 00:00:1703714503.296883 3166806 demuxer.cc:94] Demuxer::Run() on file 'packager/media/test/data/bear-640x360.mp4'.
I0000 00:00:1703714503.296935 3166806 demuxer.cc:160] Initialize Demuxer for file 'packager/media/test/data/bear-640x360.mp4'.
I0000 00:00:1703714503.307072 3166807 local_file.cc:48] Read 65536 return 65536 error 0
I0000 00:00:1703714503.307172 3166807 local_file.cc:48] Read 65536 return 65536 error 0
I0000 00:00:1703714503.307184 3166806 mp4_media_parser.cc:928] Changing state: 1
I0000 00:00:1703714503.307219 3166807 local_file.cc:48] Read 65536 return 65536 error 0
I0000 00:00:1703714503.307254 3166806 local_file.cc:48] Read 16 return 16 error 0
I0000 00:00:1703714503.307264 3166807 local_file.cc:48] Read 65536 return 65536 error 0
I0000 00:00:1703714503.307278 3166806 local_file.cc:48] Read 16 return 16 error 0
I0000 00:00:1703714503.307299 3166806 offset_byte_queue.cc:29] Buffer pushed. head=0 tail=65536
```

I do not see what it does different if at all to explain why it has verbose logging but my invocation from CLI does not.

I've tried the build I created on 2 different systems (Debian+Ubuntu) and in different shells (zsh+bash) just in case it makes a difference for some reason, but it does not appear that way. I do not know what else I can try to rule out an error on my end. The previous shaka build (v2.6.1) works fine with the same arguments.

What is the expected result?

```
[1227/135446:INFO:demuxer.cc(89)] Demuxer::Run() on file 'testing.mp4'.
[1227/135446:INFO:demuxer.cc(155)] Initialize Demuxer for file 'testing.mp4'.
[1227/135446:VERBOSE2:local_file.cc(118)] Read 65536 return 65536 error 0
[1227/135446:VERBOSE2:local_file.cc(118)] Read 16 return 16 error 0
[1227/135446:VERBOSE2:local_file.cc(118)] Read 16 return 16 error 0
[1227/135446:VERBOSE2:local_file.cc(118)] Read 16 return 16 error 0
[1227/135446:VERBOSE2:mp4_media_parser.cc(371)] Skipping top-level box: ftyp
[1227/135446:VERBOSE2:mp4_media_parser.cc(371)] Skipping top-level box: free
[1227/135446:VERBOSE2:box_reader.cc(82)] Child mvhd size 0x6c
[1227/135446:VERBOSE2:box_reader.cc(82)] Child pssh size 0x28c
[1227/135446:VERBOSE2:box_reader.cc(82)] Child pssh size 0x79
[...]

File "testing.mp4":
Found 1 stream(s).
Stream [0] type: Video
 codec_string: hev1.2.4.L150.90
 time_scale: 24
 duration: 183847 (7660.3 seconds)
 is_encrypted: true
 codec: H265
 width: 3840
 height: 1920
 pixel_aspect_ratio: 1:1
 trick_play_factor: 0
 nalu_length_size: 4

[1227/135446:VERBOSE2:mp4_media_parser.cc(371)] Skipping top-level box: sidx
[1227/135446:VERBOSE2:box_reader.cc(82)] Child mfhd size 0x10
[1227/135446:VERBOSE2:box_reader.cc(82)] Child traf size 0x505
[1227/135446:VERBOSE2:box_reader.cc(82)] Child tfhd size 0x1c
[1227/135446:VERBOSE2:box_reader.cc(82)] Child tfdt size 0x14
[1227/135446:VERBOSE2:box_reader.cc(82)] Child trun size 0x198
[1227/135446:VERBOSE2:box_reader.cc(82)] Child saiz size 0x11
[1227/135446:VERBOSE2:box_reader.cc(82)] Child saio size 0x14
[1227/135446:VERBOSE2:box_reader.cc(82)] Child senc size 0x310
Packaging completed successfully.
[1227/135446:VERBOSE2:local_file.cc(118)] Read 65536 return 65536 error 0
```

What happens instead?

```

File "testing.mp4":
Found 1 stream(s).
Stream [0] type: Video
 codec_string: hev1.2.4.L150.90
 time_scale: 24
 duration: 183847 (7660.3 seconds)
 is_encrypted: true
 codec: H265
 width: 3840
 height: 1920
 pixel_aspect_ratio: 1:1
 trick_play_factor: 0
 nalu_length_size: 4

Packaging completed successfully.
```

### PR DESCRIPTION
**Pull request by joeyparrish**
According to a comment in
packager/third_party/abseil-cpp/source/absl/log/CMakeLists.txt, many linkers will strip the contents of absl::log_flags because its symbols symbols are only used in a global constructor, and that for now, clients should link using
$<LINK_LIBRARY:WHOLE_ARCHIVE,absl::log_flags>.

Closes #1325

### CODE REVIEW

**Comment by joeyparrish** [comment]
I believe I have the docker builds fixed with the latest commit.  PTAL!

**Review by cosmin — APPROVED** [review]

**Comment by cosmin** [comment]
The windows shared build is failing with a

> LINK : fatal error LNK1104: cannot open file 'D:\a\shaka-packager\shaka-packager\build\packager\Release\libpackager.lib' [D:\a\shaka-packager\shaka-packager\build\packager\libpackager_static.vcxproj]

**Comment by joeyparrish** [comment]
> The windows shared build is failing with...

I've seen that before, and it doesn't make much sense, unless there is a race condition in the parallel build.  I think if I re-run the failed job, it will pass, which could also point toward timing.

**Comment by cosmin** [comment]
It's not clear why the shared windows build is trying to build libpackager static.

**Comment by joeyparrish** [comment]
> It's not clear why the shared windows build is trying to build libpackager static.

It always builds static, but only builds shared in the shared configuration.  This is ever since https://github.com/shaka-project/shaka-packager/pull/1293, but I don't remember the reasoning behind it.

**Comment by joeyparrish** [comment]
I'm going to file a new issue to look into this build flake, and I'll mention changes to the target structure as an option.

**Pull request merged**
