### PR TITLE
fix: Fix handling of non-interleaved multi track FMP4 files

### LINKED ISSUE #1213: Shaka packager doesn't handle non-interleaved multi track fragmented MP4 files correctly.
## System info
**Operating System**: Any
**Shaka Packager Version**: 
## Issue and steps to reproduce the problem
v2.6.1-634af65-release
**Packager Command**:
ffmpeg -i test.mp4 -c copy test.ismv // convert mp4 to fragmented mp4
packager "in=test.ismv,stream=audio,out=audio.mp4" "in=test.ismv,stream=video,out=video.mp4" --mpd_output a.mpd

Extra steps to reproduce the problem?
(1)
convert MP4 to fragmented MP4 (alternate audio/video tracks)
ffmpeg -i test.mp4 -c copy test.ismv // convert mp4 to fragmented mp4

(2)
packager "in=test.ismv,stream=audio,out=audio.mp4" "in=test.ismv,stream=video,out=video.mp4" --mpd_output a.mpd

What is the expected result?
the packager succeeds.

What happens instead?
A ton of warnings about timestamps gaps/overlaps and the playback doesn't work.

The issue is that shaka mixes the timestamps of audio and video together due to bug in the TrackRunIterator.

### PR DESCRIPTION
**Pull request by duggaraju**
Do not assume that each fragment contains all tracks. 
Use track id instead of index to pick the correct timestamp.

Fixes #1213

### CODE REVIEW

**Review by joeyparrish — CHANGES_REQUESTED** [review]
@duggaraju, could you add a unit test of some kind for this?

**Comment by joeyparrish** [comment]
The fix looks good otherwise.  Thanks for contributing!

**Comment by duggaraju** [comment]
Thnaks. Let me take a shot at the unit tests and update the PR.

**Comment by duggaraju** [comment]
Added a simple unit tests.

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
It seems that the tests crash with an out-of-bounds index.  Please fix the tests!

**Review by joeyparrish — CHANGES_REQUESTED** [review]
Please fix crashing in the tests.

**Comment by duggaraju** [comment]
@joeyparrish  let me know if the changes look ok.

**Comment by cosmin** [comment]
assuming the tests pass this looks good to me

**Review by cosmin — APPROVED** [review]

**Comment by duggaraju** [comment]
@joeyparrish  any concerns?

**Comment by joeyparrish** [comment]
Looks good to me

**Review by joeyparrish — APPROVED** [review]

**Pull request merged**
