### PR TITLE
fix: Prevent crash in GetEarliestTimestamp() if periods are empty

### LINKED ISSUE #1172: Segmentation fault on shaka::Period::GetAdaptationSets()
## System info
Ubunto 22.04
Shaka Packager Version: d5ca6e84e6ccd543dc9a79ccc8d07b702010f491

## Issue and steps to reproduce the problem

This happened on a production server, not sure what have been the exact conditions for reproducing the problem.

This is the back trace of the segmentation fault:

```
Thread 1 (Thread 0x7fb207d7f7c0 (LWP 1825)):
#0  0x00007fb1ee344894 in shaka::Period::GetAdaptationSets[abi:cxx11]() const () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#1  0x00007fb1ee1d4e36 in shaka::MpdBuilder::GetEarliestTimestamp(double*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#2  0x00007fb1ee1d60ad in shaka::MpdBuilder::AddDynamicMpdInfo(shaka::xml::XmlNode*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#3  0x00007fb1ee1d7145 in shaka::MpdBuilder::GenerateMpd() () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#4  0x00007fb1ee1d7466 in shaka::MpdBuilder::ToString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#5  0x00007fb1ee1d455e in shaka::WriteMpdToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, shaka::MpdBuilder*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#6  0x00007fb1ee1cb00d in shaka::SimpleMpdNotifier::Flush() () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
```

https://github.com/shaka-project/shaka-packager/blob/576889eecc1b7585c8f8d2f294f8d43590cced1e/packager/mpd/base/mpd_builder.cc#L351

Somehow the `periods`  are empty, causing the crash. There is a DCHECK in place, but that doesn't prevent the code from crashing.

### PR DESCRIPTION
**Pull request by murillo128**
While I have not yet found why the periods are empty, this will prevent shaka from seg faulting

Fixes #1172

### CODE REVIEW

**Comment by joeyparrish** [comment]
@murillo128, could you please fix any build and/or linter errors?

**Comment by joeyparrish** [comment]
@murillo128, you have trailing whitespace in your change, but you did not give me rights to edit your PR to fix it.  Please delete the trailing whitespace.

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
Thanks!

**Comment by murillo128** [comment]
thank you  too Joey!

**Pull request merged**
