### PR TITLE
fix: Proposed fix for #1316

### PR DESCRIPTION
**Pull request by synologic**
Fixes check in AesCbcEncryptor::CryptInternal which breaks CBCS encryption

### CODE REVIEW

**Comment by cosmin** [comment]
The right fix is to update the definition of required ciphertext size. Currently it claims it needs to be one block larger than the real size because of implementation details mbedtls. This needs to be verified, and hopefully it's either not accurate, an alternative api could be used with mbedtls or we need to switch away from mbedtls if there is no workaround.

**Comment by synologic** [comment]
Switching away from mbedtls it's probably not a 5 minute job. Not having Fairplay, currantly, is bad.
You're saying that porting AES to mbedtls was not done properly ?

**Comment by cosmin** [comment]
Yes, there are some known issues currently with the mbedtls implementation in main, please use latest 2.6.1 release until this is resolved,

**Comment by synologic** [comment]
For my needs, i will stick to this fix on the latest main.
There are notable differences (I am not sure how/when this changed) between 2.6.1 memory bandwidth usage and the latest main, but i'm seeing considerable drops in memory read/writes, as a matter of fact, memory traffic dropped about 3.5x just by using the latest main, which makes high density packaging much more efficient.

**Comment by cosmin** [comment]
@synologic  what I believe to be the correct fix for this is in the `fix-integration-tests` if you want to give that a shot. Unless the current state of `main` that branch passes all integration tests so I have reasonable confidence that it should work for all scenarios. Due to the holidays it will take some time to get that reviewed and merged (and split into several smaller pull requests) but feel free to report any problems you find on that branch and I'll take a look.

**Pull request closed without merging**
